---
title: "Our first interview"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is our first ever interview. Connor, a first-year PhD student at the University of Nottingam.

## So, tell us a bit about yourself

At present, I am studying MRes Ecology and Conservation at the University of Brighton, in the UK. My research interests are interdisciplinary and include estimating species extinction risk, the illegal wildlife trade and the ecology, conservation and welfare of raptors and owls. I am an advocate of citizen science, conservation optimism and enjoy learning new techniques and technologies to answer ecological questions and find solutions to conservation challenges.

## How did you get into the field of wildlife trade?

By accident! I have been working with and studying birds of prey for many years and whilst volunteering for a conservation project focused on the endangered Egyptian Vulture (Neophron percnopterus) in Bulgaria, I learned about the bush meat trade in various regions of sub-Saharan Africa. I found myself scouring peer-reviewed literature for more information on the global trade of birds of prey but found relatively little – but why was this the case?
Until then, the majority of the wildlife trade literature understandably focused on more focal species or products derived from them, for example ivory, rhino horn and tiger skins. However, a search on the CITES Trade Database revealed that the global legal trade in birds of prey was increasing over time, with some countries being notable importers of live birds across the globe. There was yet to be a study highlighting trends in the legal trade of birds of prey at a global-scale, feeling courageous I decided to approach some colleagues of mine and we wrote our first paper. From our initial study and from learning the limitations associated with using data derived from the CITES Trade Database, we were only able to report part of the picture – the regulated, legal side of the global trade in birds of prey. The illegal side remains unregulated, occurring ‘underground’ and out sight from the authorities – but how hidden is it?
The illegal wildlife trade is now shifting online (Siriwat & Nijman, 2020), the shift from more traditional trading methods (e.g. local markets) is favourable for illicit sellers allowing them to reach a wider customer audience whilst remaining anonymous. I was keen to further understand the trade dynamics within the illegal trade of birds of prey to help guide future species protection and conservation activities. We conducted snapshot surveys of the illegal birds of prey trade on Facebook in Thailand; a trade hotspot (see Panter & White, 2020). Our findings provided evidence that chicks are sourced from the wild and sold on social media – this should not be happening.

##Why do people want to keep raptors/falcons?

Humans have had a long historical relationship with birds of prey and the origins of falconry in Europe currently date back to the middle ages. Falconry is seen as a sign of wealth in some countries and has been preserved as part of the cultural and sporting heritage of the United Arab Emirates. From our initial study, Japan was the largest global importer of birds of prey most notably owls (see Panter et al. 2019). We suspect that this demand is driven by the Kawaii trend also referred to as Japan’s “cute culture” (Vall-llosera & Su, 2019). There are many legitimate breeders that supply the demand for birds used in falconry or the pet trade often with exceptionally high animal welfare standards. However, the illegal trade in birds of prey poses global conservation and animal welfare concerns which cannot be ignored. 
##What are gaps in the field of raptor trade?

Currently, there is still a lack of baseline trade data surrounding the illegal birds of prey trade. This is also true for the majority of other traded taxa. Baseline data from both physical and online markets and analysis of official wildlife seizure data allows researchers and authorities to better understand the dynamics of the illegal wildlife trade. Evidence from these data should be used to develop improved legislation and enforcement action which currently remains inadequate. A new report by TRAFFIC emphasises that “existing legislation does not consider wildlife trafficking a ‘serious crime’” despite it being one of the most lucrative illicit businesses globally (Charity & Ferreira 2020) . Law makers and governments can only improve wildlife protection legislation if they have the data which allows them to do so.

##Further reading

Charity, S. &amp; Ferreira, J.M. (2020). Wildlife Trafficking in Brazil. TRAFFIC International,
Cambridge, United Kingdom.

Panter, C.T. &amp; White, R.L. (2020). Insights from social media into the illegal trade of wild raptors
in Thailand. TRAFFIC Bulletin, 32(1): 5-12.

Panter, C.T., Atkinson, E.D. &amp; White, R.L. (2019). Quantifying the global legal trade in CITES-
listed raptors and owls for commercial purposes over a 40-year period. Avocetta, 43(1): 23-36.

Siriwat, P. &amp; Nijman, V. (2020). Wildlife trade shifts from brick-and-mortar markets to virtual
marketplaces: A case study of birds of prey trade in Thailand. Journal of Asia-Pacific
Biodiversity, 10.1016/j.japb.2020.03.012

Vall-llosera, M. &amp; Su, S. (2019). Trends and characteristics of imports of live CITES-listed bird
species into Japan. Ibis, 161: 590-604.


